### ISSUE TITLE
HyperSpy Bundle Portable Version

### ISSUE THREAD

**Issue by andreiasil94** [hyperspy/hyperspy-bundle#73] opened 2023-03-01 15:02 UTC
Does Portable Version have the lastest version of HyperSpy? Because I want to open data with .elid that is available in latest version however it gives error "this file format is not supported"

**Comment by hakonanes** [comment] 2023-03-01 15:14
Hi @andreiasil94,

looking at the [HyperSpy changelog](http://hyperspy.org/hyperspy-doc/current/user_guide/changes.html#v1-6), it seems like read support for this format was introduced in version 1.6. Which version of HyperSpy do you have? You can check this in Python with

```python
import hyperspy.api as hs
print(hs.__version__)
```

The latest version of the bundle (2022.10.31) should have HyperSpy version 1.7.3, the latest release.

**Comment by hakonanes** [comment] 2023-03-01 15:52
Thank you for printing the error traceback. It seems like your file is in an .elid format of version greater than 2, which isn't readable by HyperSpy yet...

I suggest to open a new issue in HyperSpy explaining your problem.

**Comment by ericpre** [comment] 2023-03-01 18:03
Closing as this is a duplicate of https://github.com/hyperspy/rosettasciio/issues/82.

**Closed by ericpre** 2023-03-01 18:03 UTC
